name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
        path: master
     - run: ls master
     - run: cd $GITHUB_WORKSPACE
     - run: ls $GITHUB_WORKSPACE
     - run: sudo apt-get update
     - run: sudo apt-get install -y apt-transport-https
     - run: sudo apt-get update
     - run: sudo apt-get install -y dotnet-sdk-6.0
     - run: dotnet build
     