name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          path: master          
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: |  
              cd "$GITHUB_WORKSPACE/master/simple dotnet app"
              docker build -t minhaz1217/basic-dotnet .
              docker push minhaz1217/basic-dotnet
          
